version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "5000:5000"
    volumes:
     - .:/backend
    depends_on:
     - redis
  redis:
    image: redis:alpine