apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: talkline-deployment
  labels:
    app: dep-talkline-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-talkline-deployment
  template:
    metadata:
      labels:
        app: pod-talkline-deployment
    spec:
      containers:
        - name: talkline-deployment
          image: froghunt3r/talkline_backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi